name: "Project Update"
description: "Update item fields for projects (beta)"
author: "Austen Stone"
branding:
  icon: "edit-2"
  color: "blue"

inputs:
  project-number:
    description: "The number of the project. Get this from the URL."
    required: true
  item-id:
    description: "The item Id of the issue or pull request."
    required: true
  github-token:
    description: "The GITHUB_TOKEN secret"
    default: ${{ github.token }}
    required: false
  organization:
    description: "The organization that owns the project."
    required: false
  user:
    description: "The user that owns the project."
    required: false
  fields:
    description: "CSV fields to modify."
    required: false
  fields-value:
    description: "CSV fields values."
    required: false

runs:
  using: "node16"
  main: "dist/index.js"