name: "Add Issue/PR to Project"
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add_to_project:
    name: Add to Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: austenstone/project-add@main
        with:
          user: ${{ github.repository_owner }}
          project-number: 5
          github-token: "${{ secrets.MY_TOKEN }}"
        id: project-add
      - uses: actions/script@v6
        with:
          script: return (new Date()).toISOString().replace(/\..*Z/g, '+00:00')
          result-encoding: string
        id: get-current-time
      - uses: ./
        with:
          user: ${{ github.repository_owner }}
          project-number: 5
          github-token: "${{ secrets.MY_TOKEN }}"
          item-id: ${{ steps.project-add.outputs.id }}
          fields: Status,product,priority,last-run,Iteration,Option,Number
          field-values: todo,back-end,high,${{ steps.get-current-time.outputs.result }},[0],option1 ⭐,999